[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
prediction_market = "78LNFkZn5wjKjscWWDXe7ChmmZ9Fu1g6rhGfCJPy7BmR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/admin.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
build = "anchor build"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
